### ISSUE TITLE
After adding few annotations cannot save or download TIFF file

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-total/GroupDocs.Total-for-NET-MVC#46]
This issue is raised in https://forum.groupdocs.com/t/multiple-issues/7163/3.
This issue is related to annotation functionality in the project. When I add some annotations in the attached tiff file and then try to save or download the file, I get "Image loading failed." this error.
![image loading failed](https://user-images.githubusercontent.com/15940608/56164671-a105ab00-5fea-11e9-9017-adf99447ed6f.JPG)
[SMF01.zip](https://github.com/groupdocs-total/GroupDocs.Total-for-NET-MVC/files/3082031/SMF01.zip)

**Comment by atirtahirgroupdocs** [comment]
@Pavel-Teplitsky can you please look into this issue?

**Comment by Pavel-Teplitsky** [comment]
Hi @atirtahirgroupdocs I will check this issue and return to you.
Best regards.

**Comment by Pavel-Teplitsky** [comment]
Hi @atirtahirgroupdocs We have reproduced this issue, approximate ETA for fix release is a next week.

**Comment by Pavel-Teplitsky** [comment]
Hi @atirtahirgroupdocs We have fixed the issue. Please download latest version of the example from this repository.

Best regards.
