### ISSUE TITLE
Page(s) loading issue when preloadPageCount set to 1

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-total/GroupDocs.Total-for-NET-MVC#47]
This issue is raised in https://forum.groupdocs.com/t/multiple-issues/7163/3.
If I do following changes in configuration.yml:
In viewer section - **htmlMode: true to false** and **preloadPageCount: 0 to 1**
In annotation section - **preloadPageCount: 0 to 1**
After I select the tiff file using browse option it show the 1st page correctly, and on rest of pages it shows like “Loading…".
See the screenshot attached.
![preloadPageCountIssue2](https://user-images.githubusercontent.com/15940608/56206463-eadfa700-6065-11e9-8eaa-a9799f919466.PNG)

**Comment by atirtahirgroupdocs** [comment]
@Pavel-Teplitsky please look into this issue. Thanks

**Comment by Pavel-Teplitsky** [comment]
Hi @atirtahirgroupdocs I will check it. 

Best regards.

**Comment by Pavel-Teplitsky** [comment]
Hi @atirtahirgroupdocs We have fixed the issue. Please pull the latest changes.
