### ISSUE TITLE
Issue in printing the annotated file

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-total/GroupDocs.Total-for-NET-MVC#70]
Hi,

I am using [this](https://drive.google.com/file/d/18WWLJjbcIy0f6aNPg8dRgCJJJqijqvrJ/view?usp=sharing) multiff file. I can successfully open it, annotate and download it. But when try to print. There are following two issues:

- Print layout is note correct
- If I close print dialog box and try to print again, I get this message 
![print error](https://user-images.githubusercontent.com/32895798/65056636-a8125a00-d98a-11e9-8616-9ac4fbcbb070.JPG)
- And the source file vanishes from the directory 

Thanks

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs the bug with deleting source file was fixed in the related PR.
To get the expected print view could you please try to use common print settings like `Scale` and `Paper size` in your operating system?
